### ISSUE TITLE
希望提供MD版本

### ISSUE THREAD

**Issue by AwsomeThomas** [scutan90/DeepLearning-500-questions#1]

**Comment by sjsdfg** [comment]
同希望提供MD版本和PDF双版本，这样可以提交PR对内容进行修改

**Comment by sjsdfg** [comment]
@scutan90 同希望提供MD版本和PDF双版本，这样可以提交PR对内容进行修改

**Comment by scutan90** [comment]
暂时不提供word版本，待内容完善后，提供，谢谢

**Comment by scutan90** [comment]
如读者有兴趣，可以合作，后续也可成书。

**Comment by noeagles** [comment]
markdown 版本便于pr

**Comment by SmirkCao** [comment]
可以文档输出添加行号
然后repo加一个issue的模板

有问题或者改进建议提issue.

**Comment by scutan90** [comment]
好像我之前有word版本，上传后公式会变

**Comment by scutan90** [comment]
哪位愿意编辑markdown 版，我可以把word版本给他编辑，然后大家进一步完善编辑。这样怎么样？
scutjy2015@163.com

**Comment by sjsdfg** [comment]
我是真的好奇这个项目怎么突然火起来的。
当初我点star的时候才 98 个。
后面这几个月峰值不过 180+
结果这两天一下窜到 800+。 这是经历了什么

**Comment by scutan90** [comment]
> 我是真的好奇这个项目怎么突然火起来的。
> 当初我点star的时候才 98 个。
> 后面这几个月峰值不过 180+
> 结果这两天一下窜到 800+。 这是经历了什么

经查，中科院自动化所和北邮的一位老师，分享后，就火了，我自己都惊

**Comment by scutan90** [comment]
> @scutan90 同希望提供MD版本和PDF双版本，这样可以提交PR对内容进行修改

可以一起编辑MD吗？scutjy2015@163.com

**Comment by scutan90** [comment]
请联系scutjy2015@163.com　；　加微信Tan：tan_weixin88

**Comment by sjsdfg** [comment]
> > @scutan90 同希望提供MD版本和PDF双版本，这样可以提交PR对内容进行修改
> 
> 可以一起编辑MD吗？[scutjy2015@163.com](mailto:scutjy2015@163.com)

不了，那时候还是学生。有很多时间可以帮做
现在要去实习了，没时间了

**Comment by clhne** [comment]
> 我是真的好奇这个项目怎么突然火起来的。
> 当初我点star的时候才 98 个。
> 后面这几个月峰值不过 180+
> 结果这两天一下窜到 800+。 这是经历了什么

你要相信微信公众号的力量~

**Comment by sjsdfg** [comment]
> > 我是真的好奇这个项目怎么突然火起来的。
> > 当初我点star的时候才 98 个。
> > 后面这几个月峰值不过 180+
> > 结果这两天一下窜到 800+。 这是经历了什么
> 
> 你要相信微信公众号的力量~

其实我也想过是哪个公众号推了一下，但是我搜了一下github的链接。没有找到相应的推文 
可以把文章地址发一下么

**Comment by aa12356jm** [comment]
好多知名微信号都在推这个库，AI科技大本营等等

**Comment by sjsdfg** [comment]
> AI科技大本营

搜不到。。。能发下地址么
也不知道那些小编早干嘛去了。。。

**Comment by clhne** [comment]
> > > 我是真的好奇这个项目怎么突然火起来的。
> > > 当初我点star的时候才 98 个。
> > > 后面这几个月峰值不过 180+
> > > 结果这两天一下窜到 800+。 这是经历了什么
> > 
> > 
> > 你要相信微信公众号的力量~
> 
> 其实我也想过是哪个公众号推了一下，但是我搜了一下github的链接。没有找到相应的推文
> 可以把文章地址发一下么

你找推文搜github干嘛？
[《深度学习500问》，川大优秀毕业生的诚意之作](https://mp.weixin.qq.com/s?__biz=MzI0ODcxODk5OA==&mid=2247498748&idx=1&sn=5bea3d818c6bf15ce2a8a715932fac0f&chksm=e99ec805dee94113020efbafe05d6f3ab09c237e2fe8a64cc7b173876e745ebb6b3ad57afd23&scene=21#wechat_redirect)

**Comment by sjsdfg** [comment]
> > > > 我是真的好奇这个项目怎么突然火起来的。
> > > > 当初我点star的时候才 98 个。
> > > > 后面这几个月峰值不过 180+
> > > > 结果这两天一下窜到 800+。 这是经历了什么
> > > 
> > > 
> > > 你要相信微信公众号的力量~
> > 
> > 
> > 其实我也想过是哪个公众号推了一下，但是我搜了一下github的链接。没有找到相应的推文
> > 可以把文章地址发一下么
> 
> 你找推文搜github干嘛？
> [《深度学习500问》，川大优秀毕业生的诚意之作](https://mp.weixin.qq.com/s?__biz=MzI0ODcxODk5OA==&mid=2247498748&idx=1&sn=5bea3d818c6bf15ce2a8a715932fac0f&chksm=e99ec805dee94113020efbafe05d6f3ab09c237e2fe8a64cc7b173876e745ebb6b3ad57afd23&scene=21#wechat_redirect)

你这疑问真的很奇怪。。我当然用谷歌搜的好吧

**Comment by sjsdfg** [comment]
> > > > 我是真的好奇这个项目怎么突然火起来的。
> > > > 当初我点star的时候才 98 个。
> > > > 后面这几个月峰值不过 180+
> > > > 结果这两天一下窜到 800+。 这是经历了什么
> > > 
> > > 
> > > 你要相信微信公众号的力量~
> > 
> > 
> > 其实我也想过是哪个公众号推了一下，但是我搜了一下github的链接。没有找到相应的推文
> > 可以把文章地址发一下么
> 
> 你找推文搜github干嘛？
> [《深度学习500问》，川大优秀毕业生的诚意之作](https://mp.weixin.qq.com/s?__biz=MzI0ODcxODk5OA==&mid=2247498748&idx=1&sn=5bea3d818c6bf15ce2a8a715932fac0f&chksm=e99ec805dee94113020efbafe05d6f3ab09c237e2fe8a64cc7b173876e745ebb6b3ad57afd23&scene=21#wechat_redirect)

推文里面要是不放github链接。。你们是怎么找过来的

**Comment by anonymone** [comment]
问题已经解决，issues close。各位还可以继续在close的issues 中交流~ ❤️
