### ISSUE TITLE
字错了😂

### ISSUE THREAD

**Issue by dhgdhg** [scutan90/DeepLearning-500-questions#10]
矩阵的F范数：矩阵的各个元素平方之和再开平方根，它通常也叫做矩阵的L2范数，它的有点在它是一个凸函数，可以求导求解，易于计算

优点吧

**Comment by scutan90** [comment]
> 矩阵的F范数：矩阵的各个元素平方之和再开平方根，它通常也叫做矩阵的L2范数，它的有点在它是一个凸函数，可以求导求解，易于计算
> 
> 优点吧

可以修改后pr，我merge吗？

**Comment by dhgdhg** [comment]
修改PDF吗?还是其他 我不太懂
不过建议以后Md可以做成这样![image](https://user-images.githubusercontent.com/18322327/47405382-dc35c880-d783-11e8-8e50-b380a6e939b2.png)

**Comment by scutan90** [comment]
> 修改PDF吗?还是其他 我不太懂
> 不过建议以后Md可以做成这样![image](https://user-images.githubusercontent.com/18322327/47405382-dc35c880-d783-11e8-8e50-b380a6e939b2.png)

这个很好的建议，等基础版出来了，就修改。因为现在是不同的伙伴们在负责

**Comment by ABadCandy** [comment]
字错+1:  第一章数学基础第二页：向量的正无穷范数： 向量的所有元素的绝对值中最大的： 上述向量 a 的负无穷范数结果就是： 10。  后面的负应该为正

**Comment by CoderOverflow** [comment]
已修正
