### ISSUE TITLE
2.40.10 ROC曲线内容有一处错误

### ISSUE THREAD

**Issue by ynxia** [scutan90/DeepLearning-500-questions#126]
“再以假正率为纵坐标、真正率为横坐标绘制成曲线”应改为“再以假正率为横坐标、真正率为纵坐标绘制成曲线”

**Comment by scutan90** [comment]
> 
> 
> “再以假正率为纵坐标、真正率为横坐标绘制成曲线”应改为“再以假正率为横坐标、真正率为纵坐标绘制成曲线”

谢谢，后面如果再有错误，可否之间修改MD文件，提交，谢谢哈

**Comment by CoderOverflow** [comment]
已修正
