### ISSUE TITLE
有的图片不显示呢，

### ISSUE THREAD

**Issue by punnpkin** [scutan90/DeepLearning-500-questions#129]
2.6  第4小标题

**Comment by scutan90** [comment]
> 
> 
> 2.6 第4小标题

好的，欢迎修改PR哈，非常谢谢

**Comment by zhaoforever** [comment]
> > 2.6 第4小标题
> 
> 好的，欢迎修改PR哈，非常谢谢

很多公式也不能显示，求教下为什么？：
​	
设函数$z=f(x,y)$在点$(x_0,y_0)$的领域内有定义，当$y=y_0$时，$z$可以看作关于$x$的一元函数$f(x,y_0)$，若该一元函数在$x=x_0$处可导，即有 $$ \lim_{\Delta x \to 0}{\frac{f(x_0+\Delta x,y_0)-f(x_0,y_0)}{\Delta x}}=A $$ ​	函数的极限$A$存在。那么称$A$为函数$z=f(x,y)$在点$(x_0,y_0)$处关于自变量$x$的偏导数，记作$f_x(x_0,y_0)$或$\frac{\eth z}{\eth x}|{y=y_0}^{x=x_0}$或$\frac{\eth f}{\eth x}|{y=y_0}^{x=x_0}$或$z_x|_{y=y_0}^{x=x_0}$。

**Comment by pumpkinpies** [comment]
可能不支持内嵌公式？ 建议pull到本地看

> > > 2.6 第4小标题
> > 
> > 
> > 好的，欢迎修改PR哈，非常谢谢
> 
> 很多公式也不能显示，求教下为什么？：
> ​
> 设函数$z=f(x,y)$在点$(x_0,y_0)$的领域内有定义，当$y=y_0$时，$z$可以看作关于$x$的一元函数$f(x,y_0)$，若该一元函数在$x=x_0$处可导，即有 $$ \lim_{\Delta x \to 0}{\frac{f(x_0+\Delta x,y_0)-f(x_0,y_0)}{\Delta x}}=A $$ ​	函数的极限$A$存在。那么称$A$为函数$z=f(x,y)$在点$(x_0,y_0)$处关于自变量$x$的偏导数，记作$f_x(x_0,y_0)$或$\frac{\eth z}{\eth x}|{y=y_0}^{x=x_0}$或$\frac{\eth f}{\eth x}|{y=y_0}^{x=x_0}$或$z_x|_{y=y_0}^{x=x_0}$。

可能不支持latex？公式？ 建议pull到本地看

**Comment by CoderOverflow** [comment]
@punnpkin  根据主readme提示，本地安装typora 并设置环境即可
