### ISSUE TITLE
建议完善markdown书写规范

### ISSUE THREAD

**Issue by SubsonBigod** [scutan90/DeepLearning-500-questions#140]
为了更好的体验，建议完善书写规范。
例如（建议）：
1. 公式块单独成行，以便其能够居中。
e.g. $$a+b=c$$改成
$$
a+b=c
$$
当然，嵌入式公式直接使用$a+b=c$即可。
2. 段落单独成行，换行符为回车符。
许多地方的段落结束都是向下箭头，其复制到其他地方就导致段落信息损失。（ch1中大部分都是这样）
向下箭头换行号叫做手工换行符，虽然在排版上将同一段落的内容分成不同的部分，但是都属于同一段落，段落格式的属性都是一样的。
3. ……

**Comment by scutan90** [comment]
> 为了更好的体验，建议完善书写规范。
> 例如（建议）：
> 
>     1. 公式块单独成行，以便其能够居中。
>        e.g. $$a+b=c$$改成
>        $$
>        a+b=c
>        $$
>        当然，嵌入式公式直接使用$a+b=c$即可。
> 
>     2. 段落单独成行，换行符为回车符。
>        许多地方的段落结束都是向下箭头，其复制到其他地方就导致段落信息损失。（ch1中大部分都是这样）
>        向下箭头换行号叫做手工换行符，虽然在排版上将同一段落的内容分成不同的部分，但是都属于同一段落，段落格式的属性都是一样的。
> 
>     3. ……

１，不错；２，为什么要复制呢？可以在md版本修改提交，导出；欢迎一起完善，不做坐享其成者

**Comment by SubsonBigod** [comment]
一个比喻，当使用不同的文本编辑器打开，可能会损失段落信息（例如使用记事本打开）
