### ISSUE TITLE
第四章缺少图片?

### ISSUE THREAD

**Issue by LarT2P** [scutan90/DeepLearning-500-questions#155]
https://github.com/scutan90/DeepLearning-500-questions/blob/master/ch4_%E7%BB%8F%E5%85%B8%E7%BD%91%E7%BB%9C/%E7%AC%AC%E5%9B%9B%E7%AB%A0_%E7%BB%8F%E5%85%B8%E7%BD%91%E7%BB%9C.md#474-inception-v4

这里是缺了个v4的图吧?

---

感谢贡献.

**Comment by CoderOverflow** [comment]
已修正
