### ISSUE TITLE
卷积概念错误

### ISSUE THREAD

**Issue by Godricly** [scutan90/DeepLearning-500-questions#158]
卷积概念错了，卷积神经网络算的不是卷积，是相关

**Comment by Morde-kaiser** [comment]
> 卷积概念错了，卷积神经网络算的不是卷积，是相关

卷积和相关的区别在于对卷积核进行了翻转。严格意义上来说，CNN计算的确实是相关，不过目前深度学习领域对于这两个概念没有刻意去区分。在信号里面会刻意区分。所以如果再解释一波相关，容易让概念复杂化
