### ISSUE TITLE
2.6 2.14

### ISSUE THREAD

**Issue by evelynyhc** [scutan90/DeepLearning-500-questions#174]
2.6 第四点最后的图片和文字之间最好加个回车。
2.14 第一点中内容错了

**Comment by anonymone** [comment]
你能具体指出一下错误的内容吗？最好还能提供一下，修改的内容。:heart:

**Comment by evelynyhc** [comment]
逻辑回归是判别模型，朴素贝叶斯是生成模型
不过后来我才看到其他人也提到了，可能是重复了

发自我的 iPhone

在 2018年11月13日，下午10:03，Severus <notifications@github.com<mailto:notifications@github.com>> 写道：


你能具体指出一下错误的内容吗？最好还能提供一下，修改的内容。❤️

**Comment by CoderOverflow** [comment]
已修正
