### ISSUE TITLE
请求添加至微信群

### ISSUE THREAD

**Issue by Mercurise** [scutan90/DeepLearning-500-questions#18]
Hi, 感谢分享，刚想加微信群发现已满，可否把我加进去，wechat id: treelearn
多谢， have a good day.

**Comment by yf704475209** [comment]
同求拉！wx:yf704475209，谢谢啦

**Comment by scutan90** [comment]
加微信Tan： 委托人微信：HQJ199508212176; Xuwumin1203; tianyuzy

**Comment by xiaomaguohe007** [comment]
求拉微信群！wx:url_820158,感谢

**Comment by anonymone** [comment]
问题已经解决，issues close。

**Comment by Image-MF** [comment]
同上，我的微信：MFg8023

**Comment by xmuwenxiang** [comment]
同上，微信:zwxloveyou，谢谢大佬们
