### ISSUE TITLE
where is PDF version 

### ISSUE THREAD

**Issue by chelsealpt** [scutan90/DeepLearning-500-questions#187]
i look for pdf version but i just see md version 
could anybody tell  me where it is ?

**Comment by jzbcoding** [comment]
you can find them in other branch . the defaut branch is master which only provide markdown  
files. @chelsealpt

**Comment by IsoaSFlus** [comment]
@jzbcoding But there is only one branch...

**Comment by jzbcoding** [comment]
> @jzbcoding But there is only one branch...

A few days ago, there are three branches , I guess the author deleted it.Maybe the author is going to publish a book.

**Comment by IsoaSFlus** [comment]
@jzbcoding Well...
Anyway, thank you for your reply.

**Comment by Dongzhixiao** [comment]
Isn't having Markdown equivalent to having a PDF version? For example, with [vscode's Markdown Preview Enhanced plug-in](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced), you can easily generate HTML/PDF and other versions.
