### ISSUE TITLE
公式编辑出错

### ISSUE THREAD

**Issue by jzbcoding** [scutan90/DeepLearning-500-questions#188]
第二章机器学习中的2.15 线性回归与逻辑回归的区别？下面公式好像乱了，有些看不懂。

**Comment by zhaoforever** [comment]
有道云笔记打开公式都是乱的，图片也不能加载，求教一下为什么？

**Comment by xiongraorao** [comment]
TODO是怎么回事，乱码的吗？

**Comment by Amberlin1970** [comment]
你好！在第二章机器学习基础中，从2.11.3逻辑回归为什么使用对数损失函数？开始出现了很多TODO，请问这是乱码还是本身就是这个样子？

**Comment by scutan90** [comment]
不完整，缺失公式，待补充






谈继勇  Tan

研究方向：先进智能控制、计算机视觉、深度学习

email：scutjy2015@163.com

在2019年3月29日 08:50，Amberlin1970<notifications@github.com> 写道：

你好！在第二章机器学习基础中，从2.11.3逻辑回归为什么使用对数损失函数？开始出现了很多TODO，请问这是乱码还是本身就是这个样子？

**Comment by CoderOverflow** [comment]
已修正
