### ISSUE TITLE
决策树有点错误

### ISSUE THREAD

**Issue by xiami2019** [scutan90/DeepLearning-500-questions#197]

**Comment by liangzhicheng120** [comment]
> _No description provided._

能指出具体章节吗？

**Comment by scutan90** [comment]
> _No description provided._

请指出具体内容，谢谢

**Comment by xiami2019** [comment]
只看了决策树那里：
1. DLT算法伪代码出自周志华《机器学习》p74
2. 决策树算法优缺点那里：
优点第二条：要求数据集不大说法欠妥，对决策树，较大的数据集也会有效果提升
优点第六条和缺点第四条自相矛盾

**Comment by CoderOverflow** [comment]
已修正
