### ISSUE TITLE
求发布PDF版本！！！

### ISSUE THREAD

**Issue by malmly** [scutan90/DeepLearning-500-questions#218]
ipad等终端无法完美适配.md格式文档，烦请大佬提供PDF版本，不胜感激！

**Comment by Apollo1840** [comment]
谢谢

**Comment by Dongzhixiao** [comment]
有Markdown版本不就相当于有pdf版本了么？比如用vscode的[Markdown Preview Enhanced插件](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced)就可以随便生成html/pdf等各种版本了呀！

**Comment by jzbcoding** [comment]
> 有Markdown版本不就相当于有pdf版本了么？比如用vscode的[Markdown Preview Enhanced插件](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced)就可以随便生成html/pdf等各种版本了呀！

但是markdown版本有好多公式显示都是乱的，我怎样才能让他们显示正确呢？

**Comment by chaopengz** [comment]
> > 有Markdown版本不就相当于有pdf版本了么？比如用vscode的[Markdown Preview Enhanced插件](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced)就可以随便生成html/pdf等各种版本了呀！
> 
> 但是markdown版本有好多公式显示都是乱的，我怎样才能让他们显示正确呢？

使用**[Typora](https://typora.io/)**打开，也可用它导出pdf，大多数公式都可以正常显示。
如果依旧显示乱的话可以查一下该公式的LaTeX格式，有可能作者笔误了~

**Comment by jzbcoding** [comment]
> > > 有Markdown版本不就相当于有pdf版本了么？比如用vscode的[Markdown Preview Enhanced插件](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced)就可以随便生成html/pdf等各种版本了呀！
> > 
> > 
> > 但是markdown版本有好多公式显示都是乱的，我怎样才能让他们显示正确呢？
> 
> 使用**[Typora](https://typora.io/)**打开，也可用它导出pdf，大多数公式都可以正常显示。
> 如果依旧显示乱的话可以查一下该公式的LaTeX格式，有可能作者笔误了~

好的，我去试试看，谢谢了。

**Comment by sxtien** [comment]
用typora看的，有一些公式显示不出来，比如第二章讲LDA的部分

**Comment by sxtien** [comment]
> 弄了个gitbook version版本的~ https://chaopengz.gitbooks.io/deeplearning-500-questions/content/

2.14.3 二类LDA算法原理部分的公式不正常
