### ISSUE TITLE
Proper acknowledgement

### ISSUE THREAD

**Issue by astonzhang** [scutan90/DeepLearning-500-questions#228]
It's great to see a new chinese book for DL. However, I noticed that some contents are very similar to https://github.com/d2l-ai/d2l-zh 

For example:

https://github.com/scutan90/DeepLearning-500-questions/blob/master/ch15_GPU%E5%92%8C%E6%A1%86%E6%9E%B6%E9%80%89%E5%9E%8B/%E7%AC%AC%E5%8D%81%E4%BA%94%E7%AB%A0_%E5%BC%82%E6%9E%84%E8%BF%90%E7%AE%97%E3%80%81GPU%E5%8F%8A%E6%A1%86%E6%9E%B6%E9%80%89%E5%9E%8B.md

and

https://github.com/d2l-ai/d2l-zh/blob/master/chapter_appendix/buy-gpu.md

It is often recommended to acknowledge the original author. For example, people often put the following sentence at the beginning:

This section is motivated (or adapted) from xxx

or put a citation link with proper paraphrase of the original content. Thanks.

**Comment by CoderOverflow** [comment]
移动到15章

**Comment by astonzhang** [comment]
Why is this issue closed without being resolved?
