### ISSUE TITLE
为什么涉及到符号之类的显示不规整，严重影响阅读体验

### ISSUE THREAD

**Issue by Star-in-Sky** [scutan90/DeepLearning-500-questions#244]

**Comment by ty5491003** [comment]
你需要自行下载一个markdown阅读器，然后将这个repo下载下来，用 阅读器来阅读md文件中的内容。如果解决了你的问题，请关闭此issue。

**Comment by zawdcxs** [comment]
最新的typora阅读器，单第一章，就有的公式能显示有的公式不显示。。

**Comment by zawdcxs** [comment]
![QGOIOS3TEHE4_0IP_}VO$7R](https://user-images.githubusercontent.com/31400142/54726917-13cc6380-4bb0-11e9-9fac-87935a55b5b7.png)

**Comment by ty5491003** [comment]
显然，这是你阅读器的问题，我使用在线的“作业部落”阅读器的效果如下：
<img width="447" alt="微信图片_20190321084341" src="https://user-images.githubusercontent.com/37855928/54727916-8a1f9480-4bb5-11e9-9456-be1d11535e84.png">

**Comment by lunyang** [comment]
win7，typora 0.9.66显示完美：
![image](https://user-images.githubusercontent.com/11520127/54727945-b9360600-4bb5-11e9-9acf-085c28f0a43f.png)

**Comment by zawdcxs** [comment]
要在偏好设置里选。。
![image](https://user-images.githubusercontent.com/31400142/54728141-0666a780-4bb7-11e9-8ddb-f0f3a71af754.png)

**Comment by david6666666** [comment]
有ubuntu系统的解决方法吗

**Comment by bing0037** [comment]
我用Typora 0.9.68，显示的也不对。后来，我把所有内容里的“$ ”和“ $”，全部替换为"$"，也就是把空格去掉，在vscode里面，完美显示~
![image](https://user-images.githubusercontent.com/11786011/54867072-24025f80-4db7-11e9-8cf5-6611bcf09725.png)

**Comment by zkeenly** [comment]
> 要在偏好设置里选。。就好了
> ![image](https://user-images.githubusercontent.com/31400142/54728141-0666a780-4bb7-11e9-8ddb-f0f3a71af754.png)

解决了！

**Comment by 7BigCAT** [comment]
有安卓系统的解决方案吗？pad是android8系统
