### ISSUE TITLE
第二章多处TODO

### ISSUE THREAD

**Issue by Amberlin1970** [scutan90/DeepLearning-500-questions#257]
你好！在第二章机器学习基础中，从2.11.3逻辑回归为什么使用对数损失函数？开始出现了很多TODO，请问这是乱码还是本身就是这个样子？
![图片](https://user-images.githubusercontent.com/37952468/55201854-e743c780-51ff-11e9-9287-6d4182e9347b.png)

**Comment by CoderOverflow** [comment]
已订正

**Comment by CoderOverflow** [comment]
已订正
