### ISSUE TITLE
迁移到专用的博客系统里？github 上Latex公式支持的不太好

### ISSUE THREAD

**Issue by hfutzzw** [scutan90/DeepLearning-500-questions#258]

**Comment by CoderOverflow** [comment]
下载到本地使用 typora 阅读即可

**Comment by lartpang** [comment]
建议使用浏览器插件, 例如

https://chrome.google.com/webstore/detail/tex-all-the-things/cbimabofgmfdkicghcadidpemeenbffn

配置下就可以显示渲染了

**Comment by scutan90** [comment]
未经同意，严禁转载
