### ISSUE TITLE
Proper acknowledgement

### ISSUE THREAD

**Issue by astonzhang** [scutan90/DeepLearning-500-questions#269]
Reopening the issue:
https://github.com/scutan90/DeepLearning-500-questions/issues/228

**Comment by CoderOverflow** [comment]
Adding the reference to your work at the end of the chapter 15,  
please check the latest version.

Thank you for your mention.
If there are any other errors, feel free to let me know.

**Comment by astonzhang** [comment]
Thanks. Please list the other co-authors:
Aston Zhang, Mu Li, Zachary C. Lipton, and Alex J. Smola.

**Comment by CoderOverflow** [comment]
Added.
