### ISSUE TITLE
2.10.4 常见代价函数 交叉熵部分求导错误

### ISSUE THREAD

**Issue by dlmyb** [scutan90/DeepLearning-500-questions#299]
具体在：[点击跳转](https://github.com/scutan90/DeepLearning-500-questions/blob/master/ch02_%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%E5%9F%BA%E7%A1%80/%E7%AC%AC%E4%BA%8C%E7%AB%A0_%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%E5%9F%BA%E7%A1%80.md#2105-%E4%B8%BA%E4%BB%80%E4%B9%88%E7%94%A8%E4%BA%A4%E5%8F%89%E7%86%B5%E4%BB%A3%E6%9B%BF%E4%BA%8C%E6%AC%A1%E4%BB%A3%E4%BB%B7%E5%87%BD%E6%95%B0)
参考：[http://cs229.stanford.edu/notes/cs229-notes1.pdf](http://cs229.stanford.edu/notes/cs229-notes1.pdf)

**Comment by scutan90** [comment]
thanks




在2019年4月7日 10:57，Yinbin Ma<notifications@github.com> 写道：

具体在：https://github.com/scutan90/DeepLearning-500-questions/blob/master/ch02_%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%E5%9F%BA%E7%A1%80/%E7%AC%AC%E4%BA%8C%E7%AB%A0_%E6%9C%BA%E5%99%A8%E5%AD%A6%E4%B9%A0%E5%9F%BA%E7%A1%80.md#2105-%E4%B8%BA%E4%BB%80%E4%B9%88%E7%94%A8%E4%BA%A4%E5%8F%89%E7%86%B5%E4%BB%A3%E6%9B%BF%E4%BA%8C%E6%AC%A1%E4%BB%A3%E4%BB%B7%E5%87%BD%E6%95%B0
参考：http://cs229.stanford.edu/notes/cs229-notes1.pdf

**Comment by CoderOverflow** [comment]
this part of formula  refers from
http://neuralnetworksanddeeplearning.com/chap3.html

**Comment by dlmyb** [comment]
> this part of formula refers from
> http://neuralnetworksanddeeplearning.com/chap3.html

![Imgur](https://i.imgur.com/zezOik6.png)
![Imgur](https://i.imgur.com/59EaOfA.png)

**Comment by CoderOverflow** [comment]
thank you. 
the left bracket seems in the wrong position.
