### ISSUE TITLE
第十章 强化学习 有很多需要改进的地方

### ISSUE THREAD

**Issue by Yonv1943** [scutan90/DeepLearning-500-questions#479]
我只看了强化学习部分。非常失望。

**不建议任何人类通过此部分的内容学习强化学习。**

1. 知识老旧（没有2017年后的东西，要知道2018年强化学习有很多革新）
2. 引喻失义（胡乱类比，见10.1.1）
3. 文中说“强化学习和前二者的本质区别”，我反对这句话。我认为强化学习解决了稀疏奖励的问题，这是主要区别中重要的一点
4. 还有很多，我不想写。

**Comment by zky001** [comment]
> 我只看了强化学习部分。非常失望。
> 
> **不建议任何人类通过此部分的内容学习强化学习。**
> 
> 1. 知识老旧（没有2017年后的东西，要知道2018年强化学习有很多革新）
> 2. 引喻失义（胡乱类比，见10.1.1）
> 3. 文中说“强化学习和前二者的本质区别”，我反对这句话。我认为强化学习解决了稀疏奖励的问题，这是主要区别中重要的一点
> 4. 还有很多，我不想写。

你可以修改并且pr

**Comment by Yonv1943** [comment]
这个github 项目的开源协议是 GPL-3.0 License
然而，Readme.md 却用大字说“禁止转载，禁止转载，禁止转载！”

这是不是开源项目？
“你可以修改并且pr” ← 这是非常差的建议
