### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by DBX12** [scutan90/DeepLearning-500-questions#6]
Hey there,
an English translation would be nice for us :)

**Comment by scutan90** [comment]
> I am going to translate it into English. @scutan90 could we work on this?

As the content is not perfect now, we are in a hurry to sort it out. After the content is completed, we can cooperate with the translation. Is that ok?

**Comment by scutan90** [comment]
> Hey there,
> an English translation would be nice for us :)

As the content is not perfect now, we are in a hurry to sort it out. After the content is completed, we can cooperate with the translation. Is that ok?

**Comment by scutan90** [comment]
We are working on editing the MD version, and partners can complete the information on MD

**Comment by cbsudux** [comment]
An english version will be appreciated, even if it's not refined :)

**Comment by jeongwhanchoi** [comment]
I want this content to be translated into English in the early times. Then I want to translate it into Korean.

**Comment by cbsudux** [comment]
Great, it looks like the questions have been translated. Translating the solutions too would be very helpful.
