### ISSUE TITLE
对于超参数部分

### ISSUE THREAD

**Issue by csufangyu** [scutan90/DeepLearning-500-questions#68]
为什超参数调节部门很少呢？其实对于这一部分是目前绝大多数人困惑，如何调节超参数这是一个非常工程和玄学的问题，希望作者可以增加一些技巧!我说说我的经验吧，对于超参数最重要的是学习率，其次是batchsize，卷积核的大小在绝大多数情况下要么3*3，要么1*1，训练的时候，有点先将基础网络固定在调节，有的一起调节，这个就是一个玄学问题，有的好有的很差，希望作者多放一些超参数调节技巧吧！谢谢作者！

**Comment by scutan90** [comment]
> 为什超参数调节部门很少呢？其实对于这一部分是目前绝大多数人困惑，如何调节超参数这是一个非常工程和玄学的问题，希望作者可以增加一些技巧!我说说我的经验吧，对于超参数最重要的是学习率，其次是batchsize，卷积核的大小在绝大多数情况下要么3_3，要么1_1，训练的时候，有点先将基础网络固定在调节，有的一起调节，这个就是一个玄学问题，有的好有的很差，希望作者多放一些超参数调节技巧吧！谢谢坐着玩

恩恩，首先非常谢谢。超参数这部分，后期会做大量完善，您也可以整理内容添加到MD哈。可加微信tan_weixin88 谢谢

**Comment by CoderOverflow** [comment]
另一方面 很多深度学习的工具都在革新 以后更多的会趋向于自适应和自动化
参数这东西 领会精神就好 切莫走火入魔

**Comment by CoderOverflow** [comment]
第十四章
