### ISSUE TITLE
文件命名统一的讨论

### ISSUE THREAD

**Issue by anonymone** [scutan90/DeepLearning-500-questions#89]
感觉img文件夹的图片命名比较乱
我想把结构
改为：
```
-->img
---->ch1
------>ch1_1.png
------>ch1_2.jpg
```
@scutan90 觉得如何？

**Comment by scutan90** [comment]
> 感觉img文件夹的图片命名比较乱
> 我想把结构
> 改为：
> 
> ```
> -->img
> ---->ch1
> ------>ch1_1.png
> ------>ch1_2.jpg
> ```
> 
> @scutan90 觉得如何？

我目前规划所有章节都改：
>-->master
>--->第一章　数学基础
> ---->img
> ----->ch1
> ------->ch1_1.png
> ------->ch1_2.jpg
> ---->md
> ---->pdf
> ---->txt
> ---->其他
>--->第二章　机器学习基础
>--->第三章　深度学习基础
>--->第四章　经典网络

**Comment by anonymone** [comment]
那我先把img的整理出来。
